### Bandit config file for openssl_encrypt

# Skip test IDs explicitly - used for tests that are too noisy or not applicable
skips: ['B101', 'B404', 'B603']

# File extensions to include/exclude
exclude_dirs: ['tests', 'unittests', 'venv', '.git', '.github', 'build', 'dist']

# Define custom plugins
# plugins:
#   - some_custom_plugin

### Output settings

# Which severity levels to show
show_severity_level: all

# Per test settings
# Adjust the severity of specific test IDs
test_ids:
    # Ensure all crypto modules are carefully scrutinized
    # B303: Use of weak cryptography (MD4/MD5/SHA1)
    B303:
        level: HIGH
    # B324: Use of insecure md4, md5, or sha1 hash function.
    B324:
        level: HIGH
    # B501: Request with non-constant timeout
    B501:
        level: MEDIUM
    # B506: Use of yaml.load
    B506:
        level: HIGH
    # B311: Standard pseudo-random generators are not suitable for cryptographic purposes
    B311:
        level: HIGH
    # B110: Try, Except, Pass detected
    B110:
        level: MEDIUM

# Adjust the confidence level
confidence_level: MEDIUM

# File extension exclusion
exclude_dirs: ['.git', 'venv', 'tests', 'test_data', 'build', 'dist', 'docs']

# Baseline file for comparison (if used)
# baseline: bandit_baseline.json