#!/usr/bin/env python3
"""
Golden-fixture tests: committed recovery-slot files must keep decrypting with
their fixed recovery credentials forever. These pin the on-disk recovery-slot
format so later changes cannot silently break old files.

The fixtures were produced by openssl_encrypt itself with FIXED credentials
(committed below) and are immutable.
"""

import base64
import json
import unittest
from pathlib import Path

from openssl_encrypt.modules.crypt_core import decrypt_file
from openssl_encrypt.modules.secret_sharing import Share

_DIR = Path(__file__).parent / "testfiles" / "recovery_slots"
PASSWORD = b"1234"
CODE = "AAAAABBBBBCCCCCDDDDDEEEEEFFFFFGGGGGHHHHHIIIIIJJJJJKK"
PASSPHRASE = b"golden fixture recovery passphrase"
PLAINTEXT = (_DIR / "plaintext.bin").read_bytes()


def _meta(path):
    return json.loads(base64.b64decode(path.read_bytes().split(b":", 1)[0]))


class TestShamirKeyIdGoldenFixture(unittest.TestCase):
    """shamir_keyid.enc pins the key_id-stamped shamir slot layout.

    Generated by this line's own `add-recovery --add-shares 2-of-3` (which
    stamps the share-set id on slot and share files), so the type-native
    key_id sourcing (gitlab#280) is asserted against real producer output
    on both maintenance lines (gitlab#280 review F8; fixture shared with
    1.4.x, which lists/password-decrypts it).
    """

    KEY_ID = "832269cf-7ade-4367-9b8b-cdaf75344700"

    def test_listing_reports_the_share_set_id(self):
        from openssl_encrypt.modules.crypt_core import list_recovery_slots

        shamir = [
            s for s in list_recovery_slots(str(_DIR / "shamir_keyid.enc")) if s["type"] == "shamir"
        ]
        self.assertEqual(len(shamir), 1)
        self.assertEqual(shamir[0]["key_id"], self.KEY_ID)
        self.assertEqual(shamir[0]["threshold"], 2)
        self.assertEqual(shamir[0]["num_shares"], 3)
        # The share files carry the same set id, binding them to the slot.
        for i in (1, 2, 3):
            share = json.loads((_DIR / f"shamir_keyid_share_{i}.json").read_text())
            self.assertEqual(share["metadata"]["key_id"], self.KEY_ID)

    def test_share_based_decrypt_still_works(self):
        shares = [Share.from_file(str(_DIR / f"shamir_keyid_share_{i}.json")) for i in (1, 3)]
        self.assertEqual(
            decrypt_file(
                input_file=str(_DIR / "shamir_keyid.enc"),
                output_file=None,
                recovery_shares=shares,
                quiet=True,
            ),
            PLAINTEXT,
        )

    def test_primary_password_still_works(self):
        self.assertEqual(
            decrypt_file(
                input_file=str(_DIR / "shamir_keyid.enc"),
                output_file=None,
                password=PASSWORD,
                quiet=True,
            ),
            PLAINTEXT,
        )


class TestRecoverySlotGoldenFixtures(unittest.TestCase):
    def test_fixtures_have_slot_set(self):
        for name, typ in (
            ("recovery_code.enc", "recovery_code"),
            ("passphrase.enc", "passphrase"),
            ("shamir.enc", "shamir"),
        ):
            enc = _meta(_DIR / name)["encryption"]
            self.assertIn("dek_slots", enc, name)
            self.assertIn("dek_slots_mac", enc, name)
            self.assertEqual(enc["dek_slots"][0]["type"], typ, name)

    def test_recovery_code_fixture(self):
        self.assertEqual(
            decrypt_file(
                input_file=str(_DIR / "recovery_code.enc"),
                output_file=None,
                recovery_code=CODE,
                quiet=True,
            ),
            PLAINTEXT,
        )

    def test_passphrase_fixture(self):
        self.assertEqual(
            decrypt_file(
                input_file=str(_DIR / "passphrase.enc"),
                output_file=None,
                recovery_passphrase=PASSPHRASE,
                quiet=True,
            ),
            PLAINTEXT,
        )

    def test_shamir_fixture(self):
        shares = [
            Share.from_file(str(_DIR / "shamir_share_1.json")),
            Share.from_file(str(_DIR / "shamir_share_3.json")),
        ]
        self.assertEqual(
            decrypt_file(
                input_file=str(_DIR / "shamir.enc"),
                output_file=None,
                recovery_shares=shares,
                quiet=True,
            ),
            PLAINTEXT,
        )

    def test_primary_password_still_works(self):
        for name in ("recovery_code.enc", "passphrase.enc", "shamir.enc"):
            self.assertEqual(
                decrypt_file(
                    input_file=str(_DIR / name), output_file=None, password=PASSWORD, quiet=True
                ),
                PLAINTEXT,
                name,
            )


if __name__ == "__main__":
    unittest.main()
