#!/usr/bin/env python3
"""
End-to-end CLI tests for `decrypt --from age` (feature #5, phase 1).

Drives the real CLI against age files generated by the `age` reference
implementation (hardcoded vectors, same as test_interop_age.py): X25519 via an
--age-identity keys.txt, and scrypt via --password.
"""

import base64
import os
import shutil
import sys
import tempfile
import unittest
from unittest import mock

from openssl_encrypt.modules.crypt_cli import main as cli_main

# Reference-impl (pyrage/rage) vectors — see test_interop_age.py.
X25519_SK = "AGE-SECRET-KEY-1WK95G077CU2H2G6NCTV85NJYKESJCDL2DQPJU0QCX73NTY4F40FQC5FYNE"
X25519_CT = (
    "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd2JPbkl0NTFTc3ZzK21NZmpXVnI2Vk91WFMw"
    "YlZ5bThHTXIwbjM2R1dFCk96aCtQTEN5VGtvd0haSDYvT3NxTENZQ1l6b01HVEIyWmlCdzhYOHlZdFkK"
    "LT4gJnxWMi1ncmVhc2UgcHMKb3d5aE9QQlJReVB6Nno1L05qdXBERmxkcDVkYWoxeWlJMUhxOFhsMG5o"
    "NGhJajMxCi0tLSBlQjN1MkQwMG9HbHZuZDJZMVpRamNLMVhtUVloRnZnd1NTeHdvdlZsUHd3Cv0Smdek"
    "2sm3MD9mXSa/bST0uxWPsi/+P63nCJhKyfSG3lHOK0X4zqT6lRmegQ=="
)
SCRYPT_CT = (
    "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNjcnlwdCBOSGhsNXowWmYwcmhuTVNWS3VnbEp3IDIwCnFy"
    "b05kZ1hwcE14OTlkOXBMaE1wRmc4aEhxMkFaQk5HZlhnWDRTb2FlVFkKLS0tICt0NGNrNXU5OFY0c3gr"
    "RXZraFp1YklSZkhOZkxRb21Xd1MvcWV6RFphN0EKWFB5+/74iq+mRPO46cMGmaw8oQnjFCTVrRg3a3KN"
    "3Fv+vccEgDAmHb10"
)


class TestDecryptFromAgeCLI(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.original_argv = sys.argv

    def tearDown(self):
        sys.argv = self.original_argv
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _write(self, name, data):
        p = os.path.join(self.tmp, name)
        with open(p, "wb") as f:
            f.write(data)
        return p

    def _run(self, argv):
        sys.argv = ["crypt.py"] + argv
        so = sys.stdout
        sys.stdout = open(os.devnull, "w")
        try:
            with mock.patch("getpass.getpass", return_value=""):
                try:
                    cli_main()
                    return 0
                except SystemExit as e:
                    return e.code if isinstance(e.code, int) else (0 if e.code is None else 1)
        finally:
            sys.stdout.close()
            sys.stdout = so

    def test_x25519_to_output_file(self):
        enc = self._write("msg.age", base64.b64decode(X25519_CT))
        keys = os.path.join(self.tmp, "keys.txt")
        with open(keys, "w") as f:
            f.write(X25519_SK + "\n")
        out = os.path.join(self.tmp, "msg.txt")
        rc = self._run(
            [
                "--quiet",
                "decrypt",
                "--from",
                "age",
                "--input",
                enc,
                "--age-identity",
                keys,
                "--output",
                out,
            ]
        )
        self.assertEqual(rc, 0)
        with open(out, "rb") as f:
            self.assertEqual(f.read(), b"hardcoded KAT")

    def test_scrypt_with_password(self):
        enc = self._write("pw.age", base64.b64decode(SCRYPT_CT))
        out = os.path.join(self.tmp, "pw.txt")
        rc = self._run(
            [
                "--quiet",
                "decrypt",
                "--from",
                "age",
                "--input",
                enc,
                "--password",
                "pw-fixed",
                "--output",
                out,
            ]
        )
        self.assertEqual(rc, 0)
        with open(out, "rb") as f:
            self.assertEqual(f.read(), b"KAT scrypt")

    def test_wrong_identity_fails(self):
        enc = self._write("msg.age", base64.b64decode(X25519_CT))
        keys = os.path.join(self.tmp, "wrong.txt")
        # A valid-format but non-matching age secret key (validated encoder).
        from openssl_encrypt.unittests.test_interop_age import _scalar_to_age_secret

        wrong = _scalar_to_age_secret(os.urandom(32))
        with open(keys, "w") as f:
            f.write(wrong + "\n")
        out = os.path.join(self.tmp, "msg.txt")
        rc = self._run(
            [
                "--quiet",
                "decrypt",
                "--from",
                "age",
                "--input",
                enc,
                "--age-identity",
                keys,
                "--output",
                out,
            ]
        )
        self.assertEqual(rc, 1)
        self.assertFalse(os.path.exists(out))

    def test_scrypt_wrong_password_fails(self):
        enc = self._write("pw.age", base64.b64decode(SCRYPT_CT))
        out = os.path.join(self.tmp, "pw.txt")
        rc = self._run(
            [
                "--quiet",
                "decrypt",
                "--from",
                "age",
                "--input",
                enc,
                "--password",
                "nope",
                "--output",
                out,
            ]
        )
        self.assertEqual(rc, 1)


if __name__ == "__main__":
    unittest.main()
